### ISSUE TITLE
Numeric values are encoded incorrectly

### ISSUE THREAD

**Issue by sergseven** [crownedgrouse/jason#8] opened 2022-09-02 12:17 UTC
Expected the test(from examples) to pass:
```
?assertEqual("123.456789", jason:encode(123.456789)).
```

but the actual value is 

```
"123.456789000000001"
```

**Comment by crownedgrouse** [comment] 2022-09-02 14:16
please precise Erlang/OTP release used.

**Comment by crownedgrouse** [comment] 2023-04-22 09:23
Cannot reproduce. Please give precision on otp version, os and arch , or I will close.

**Comment by crownedgrouse** [comment] 2023-07-15 07:12
1> jason:encode(123.456789).
"123.456789"

Closing as not reproduced and lack of information.

**Closed as completed by crownedgrouse** 2023-07-15 07:12 UTC
Labels: bug
